export enum BookingStatus {
  REQUESTED = 'REQUESTED',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED',
  CANCELLED_BY_CLIENT = 'CANCELLED_BY_CLIENT',
  CANCELLED_BY_PRO = 'CANCELLED_BY_PRO',
  COMPLETED = 'COMPLETED',
  EXPIRED = 'EXPIRED',
}

export const BOOKING_STATUS_VALUES = Object.values(BookingStatus);
